services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\ApiUserPermissionsBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    KimaiPlugin\ApiUserPermissionsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
